Add Object Priority Mode Register
gbdev/hardware.inc pull request #39
Opened 2023-04-29 21:07 UTC by rbong

See: https://gbdev.io/pandocs/CGB_Registers.html?highlight=ff6c#ff6c--opri-cgb-mode-only-object-priority-mode

2023-04-29 23:09 UTC, CasualPokePlayer commented
This register effect on priority is only effective when the bootrom is unmapped [(or if one of the PGB modes are active, according to SameBoy's source)](https://github.com/LIJI32/SameBoy/blob/237e127b36eaee574e2a1d7900da21bda0775405/Core/memory.c#L1397). Once those conditions are no longer met then any more writes will not effect priority, and the register effectively just becomes a free bit of RAM.

I would assume this would be useful for homebrew bootrom authors, but otherwise perhaps the docs on this should note it is (mostly?) bootrom only?

2023-04-30 02:51 UTC, rbong commented
> This register effect on priority is only effective when the bootrom is unmapped [(or if one of the PGB modes are active, according to SameBoy's source)](https://github.com/LIJI32/SameBoy/blob/237e127b36eaee574e2a1d7900da21bda0775405/Core/memory.c#L1397). Once those conditions are no longer met then any more writes will not effect priority, and the register effectively just becomes a free bit of RAM.
> 
> I would assume this would be useful for homebrew bootrom authors, but otherwise perhaps the docs on this should note it is (mostly?) bootrom only?

Thanks, I added a short comment about that. I missed that from Pandocs.

2023-04-30 07:33 UTC, avivace approved these changes

2023-05-20 11:00 UTC, ISSOtm requested changes
Thanks!

2023-05-20 11:00 UTC, ISSOtm commented on hardware.inc
> +; -- CGB Mode Only
```suggestion
; -- CGB Only

```

2023-05-20 11:00 UTC, ISSOtm commented on hardware.inc
> +DEF OPRI_COORD EQU 1 ; Prioritize objects by x-coordinate (DMG default)
```suggestion
DEF OPRI_OAM   EQU 0 ; Prioritize objects by location in OAM (CGB Mode default)
DEF OPRI_COORD EQU 1 ; Prioritize objects by x-coordinate (Non-CGB Mode default)

```

2023-05-22 13:45 UTC, merged